services:
  - type: web
    name: crmedic
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""           
    startCommand: php artisan serve --host=0.0.0.0 --port=80
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_URL
        value: https://crmedic-os8k.onrender.com
      - key: DB_CONNECTION
        value: postgresql
      - key: DB_HOST
        value: maglev.proxy.rlwy.net
      - key: DB_PORT
        value: 56475
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: NdebmcFdQmphluWbRCtTBfOxRLhVvlUF
      - key: LOG_CHANNEL
        value: stderr
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
